### ISSUE TITLE
jaxon.debug - load error message

### ISSUE THREAD

**Issue by nevtag** [jaxon-php/jaxon-js#1]
Hi,
I get this message, if I enable debug.
The message is only on the first page call, allways.

> The jaxon.debug javascript component could not be included. Perhaps the URL is incorrect?
URL: /js/jaxon/jaxon.debug.min.js

After that, debug is working.
Looks like jaxon.debug.isLoaded isn't set, at the time you make the try check, if(jaxon.debug.isLoaded)

regards
Joc

**Comment by feuzeu** [comment]
This issue was moved to jaxon-php/jaxon-core#15
