### ISSUE TITLE
Hello I need help with the installation

### ISSUE THREAD

**Issue by bioraft-xx** [jaxon-php/jaxon-js#11]
Hello, I am a newbe with this and I need help, I installed Composer in my server and my developement macchine, I am using Apache 2.4 with PHP 7.2.4. Ok with composer installed in both my server and my machine I installed Jaxon.

but when I try to execute even the simple example I got this error:

Fatal error: Uncaught Error: Call to undefined function jaxon() in C:\Webprojects\Web_Authority_Framework\WebApp\test3.php:19 Stack trace: #0 {main} thrown in C:\Webprojects\Web_Authority_Framework\WebApp\test3.php on line 19

is the line $jaxon=jaxon();

I don't know what more I can do... I think I am missing somethin and I have the same error in my server and my development machine. I am migrating some code from Xajax and I need to migrate to PHP 7 and I think with Jaxon will be the way.

Please help and thanks.

**Comment by feuzeu** [comment]
This issue was moved to jaxon-php/jaxon-core#29
