### ISSUE TITLE
ignoring duplicate XHR requests

### ISSUE THREAD

**Issue by seba1rx** [jaxon-php/jaxon-js#13]
Hello, I would like to know if the is a way to implement in jaxon a configurable validation to prevent duplicated calls to jaxon functions in irder to deal with double click and other situations where I want to prevent double requests.

The idea is to implement this validation in jaxon and not in other parts of the code.

something like:

```
var isValidating = true

function processJaxonCall( 'jaxon_function' ){
if ( isValidating ) {
    if ( detectRunningCall ( 'jaxon_function' )  ){
        // ignore call
    }else{
        // process call
    }
}else{
    // process call
}
```

any idea??

**Comment by feuzeu** [comment]
Hi,

Jaxon does not provide this feature. However, you can implement it quite easily.

First define some js callbacks Jaxon will execute with your request.
```javascript
myCallbacks = {
    timers: [], // Required, even if not used here.
    enabled: true,
    onRequest: function() {
        myCallbacks.enabled = false;
    },
    onFailure: function() {
        myCallbacks.enabled = true;
    },
    onSuccess: function() {
        myCallbacks.enabled = true;
    }
}
```

Then register the callbacks with your PHP function or class.
```php
jaxon()->register(Jaxon::USER_FUNCTION, 'my_function', ['callback' => 'myCallbacks']);
```
At this point, Jaxon will set the enabled var on each request, but still execute the request.
You'll have to prevent Jaxon from sending the request by yourself, what you can do using the request factory.
```php
rq()->call('my_function')->when(pr()->js('myCallbacks.enabled'));
```

The only feature that can be added to Jaxon is to allow you to cancel a request in the `onRequest()` callback, so you don't need the last above step.

I'll add it in the next release, which is coming soon.

**Comment by feuzeu** [comment]
Hi,
I just commited a change on this feature on the develop branch.
I've added a new callback function named `onPrepare`, which is called before preparing the request for submit.
You can prevent the request from being submitted by setting the `ignore` attribute on the request object to `true`, as follow.

```javascript
    nodupCallbacks = {
        enableCall: true,
        onPrepare: function(request) {
            if(nodupCallbacks.enableCall == false) {
                request.ignore = true;
                return;
            }
            nodupCallbacks.enableCall = false;
        },
        onComplete: function() {
            nodupCallbacks.enableCall = true;
        }
    }
```
As you can see, the `timers` attribute is no more required.
