### ISSUE TITLE
Clarifying some things

### ISSUE THREAD

**Issue by frecervantes** [jaxon-php/jaxon-js#23]
Just for clarity, is it reliable to use version 4.x of the library? If not, what is the latest stable version?
If I'm not interested in using namespaces or autoloading, I need to install with Composer or just the library I bring from the CDN.
I am a newbie with js. sorry for these basic questions

regards

**Comment by feuzeu** [comment]
Hi,

By default, the latest 4.x PHP library is configured to load the javascript libraries from https://cdn.jsdelivr.net/gh/jaxon-php/jaxon-js@3.3/dist. So it will use the latest stable release, which is 3.3.8 now.

The main branch of this repository (javascript) is not yet stable, and not yet released.

**Comment by frecervantes** [comment]
thanks for your answer mr Feuzeu, but your your advise about the jaxon
library version send me this:

net::ERR_ABORTED 404 (Not Found)

and inside the <head> tag
<script src=" ***@***.***/dist"></
script>

any sugestion

**Comment by feuzeu** [comment]
You need to add a slash at the end of the url.
https://cdn.jsdelivr.net/gh/jaxon-php/jaxon-js@3.3/dist/
Sorry for the typo.

**Comment by frecervantes** [comment]
Thanks, I'll check it out.

Happy new year eve

**Comment by feuzeu** [comment]
> Happy new year

Thanks. Happy new year too.
