### ISSUE TITLE
what's wrongwith the code?

### ISSUE THREAD

**Issue by frecervantes** [jaxon-php/jaxon-js#24]
Hi, i'm using your code, intalled on win 10 using composer, wamp, php.7.4, just trying to see this working, migrating from xajax, but a bit confuse... this is the script.

<?php
  // Incluye el archivo Jaxon
  require_once 'vendor/autoload.php';
  use Jaxon\Jaxon;
  use function Jaxon\jaxon;

  // $jaxon = jaxon();

  function hello_world($isCaps){
      $response = jaxon()->newResponse();
      $text = ($isCaps) ? 'HELLO WORLD!' : 'Hello World!';
      $response->assign('div2', 'innerHTML', $text);
      return $response;
  }
  
  $jaxon = jaxon();
  $jaxon->register(Jaxon::CALLABLE_FUNCTION, "hello_world");
  
?>

  <!DOCTYPE html>
  <html lang="es">
  <head>
    <meta charset="UTF-8">
    <title>Aplicación Hola Mundo con Jaxon</title>
      <?= $jaxon->getJs() ?>
  </head>
  <body>
    <h3>Aplicación Hola Mundo con Jaxon</h3>
    <input type="button" value="Say Hello" onclick="jaxon_hello_world(0)" />
    <div id='div2' class=""></div>
  </body>
  </html>

error: jaxon_hello_world is not defined ??

thank for your help

regards

**Comment by feuzeu** [comment]
Hi,

Starting from v4, the global functions are namespaced.
```php
use Jaxon\jaxon;

$jaxon = jaxon();
```

You register classes and not objects.
```php
$jaxon->register(\Jaxon\Jaxon::CALLABLE_CLASS, HelloWorld::class); 
```

The changes are documented here: https://www.jaxon-php.org/docs/v4x/about/changes.html.

**Comment by frecervantes** [comment]
Mr Feuzeu, excuse my limited knowlege on js, but i'm just trying to build a functional script in order to leave xajax back. at least  using functions at the begining, but i still getting an error. may you help ?

newResponse(); $text = ($isCaps) ? 'HELLO WORLD!' : 'Hello World!'; $response->assign('div2', 'innerHTML', $text); return $response; } $jaxon = jaxon(); $jaxon->register(Jaxon::CALLABLE_FUNCTION, "hello_world"); ?> <title>Aplicación Hola Mundo con Jaxon</title> getJs() ?>
Aplicación Hola Mundo con Jaxon
error: jaxon_hello_world is not defined ??

thank you very much
regards

**Comment by feuzeu** [comment]
This is a complete example of using Jaxon like Xajax.
I usually do not recommend (because of the mix of html and js code) but since you are just migrating from Xajax.

```php
<?php
require('./vendor/autoload.php');

use Jaxon\Jaxon;
use function Jaxon\jaxon;

function hello_world($isCaps)
{
    $response = jaxon()->newResponse();
    $text = ($isCaps) ? 'HELLO WORLD!' : 'Hello World!';
    $response->assign('div1', 'innerHTML', $text);
    return $response;
}

$jaxon = jaxon();
$jaxon->register(Jaxon::CALLABLE_FUNCTION, "hello_world");

// Process the request.
if($jaxon->canProcessRequest())
{
    $jaxon->processRequest();
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Jaxon Examples</title>
</head>

<body>
    <div id="div1">&nbsp;</div>
    <input type="button" value="Say Hello" onclick="jaxon_hello_world(true)" />
</body>
<!-- Jaxon CSS -->
<?php
echo $jaxon->getCss(), "\n";
?>
<!-- Jaxon JS -->
<?php
echo $jaxon->getJs(), "\n";
?>
<!-- Jaxon script -->
<?php
echo $jaxon->getScript(), "\n";
?>
</html>
```

You can replace `jaxon_hello_world(true)` with `jaxon_hello_world(false)` to see the change.

**Comment by feuzeu** [comment]
Make sure you have this in the source code of your page.

```js
jaxon_hello_world = function() {
    return jaxon.request({ jxnfun: 'hello_world' }, { parameters: arguments });
};
```

**Comment by frecervantes** [comment]
thank you very, very much Mr. Frezeu, this is what I needed to start using the Jaxon library, fully functional, as I become more familiar with it, I am sure I will be able to use it in the best way and explore its full potential and I will surely ask for your appreciated help. 

Regards

**Comment by frecervantes** [comment]
We appreciate your help and effort in maintaining the jaxon library and any example to show the use of the different features, no matter how simple, is a great help in implementing and understanding how jaxon works. Thus, I encourage you to show, through examples, the functionalities of this great software.

again thank you very much.
