### ISSUE TITLE
Question about get debug messages on a browser window

### ISSUE THREAD

**Issue by feuzeu** [jaxon-php/jaxon-js#5]
_From @jatubio on May 7, 2017 21:35_

Hello,

When i set `$jaxon->setOption('core.debug.on', true);` some times I get the messages on a new browser window, but another times, I get the Messages sequentially as alerts box.

I do not know why this happens. Is there any way to always force the browser window for debugging messages?

Thank you

_Copied from original issue: jaxon-php/jaxon-core#17_

**Comment by feuzeu** [comment]
I've never met this issue.
Does it happen at random?

**Comment by feuzeu** [comment]
_From @jatubio on May 8, 2017 16:31_

In my web app debug messages show in browser window. But, in your example: HelloWorld, they show in alerts boxes.

**Comment by feuzeu** [comment]
Hi,
Did you modify anything in the js code?

**Comment by jatubio** [comment]
I'm sorry, I do not remember.

At the moment I am immersed in a great project that requires me full attention. In a couple of months I hope to have more free time and I can do some tests and provide more details.

**Comment by feuzeu** [comment]
I close this issue since there's no detailed information about how it happened.

**Comment by jatubio** [comment]
Hello, I researched this subject and I discovered what happens.

I'm using Google Chrome. By default, Google Chrome it's blocking popup windows and showing a warning on url bar. If popup windows is blocked, debug info is showed as a succession of alert box. If popup windows are allowed, they show on his custom html popup window.

**Comment by feuzeu** [comment]
Just got into the js code and realized that's the way its operates.
