### ISSUE TITLE
How to get returnValue?

### ISSUE THREAD

**Issue by jatubio** [jaxon-php/jaxon-js#6]
Hello, 

I have this javascript code on my page: `alert(jaxon_formRegistro(jaxon.getFormValues(frm.name,true)));`

And this one: 
```
jaxon_formRegistro = function() {
    return jaxon.request(
        { jxnfun: 'ajaxProcess' },
        { parameters: arguments }
    );
};
```

I'm getting this response:
```
Sat Aug 26 2017 15:15:40 GMT+0200 (Romance Daylight Time)
RECEIVED [status: 200, size: 157 bytes, time: 1769ms]:
{"jxnrv":true,"jxnobj":[{"cmd":"as","id":"form-errores","prop":"innerHTML","data":""},{"cmd":"as","id":"form-errores","prop":"style.display","data":"none"}]}
```

But the alert on my first javascript code is showing: 'false'. ¿How to check returnValue (`"jxnrv":true`)

Thanks

**Comment by feuzeu** [comment]
Hi,
I guess you are using asynchronous requests. In this case, your alert() function prints the return value of the Jaxon request, which is by default set to false.
You can change this value by setting `jaxon.config.defaultReturnValue = true;` before calling the Jaxon function in the web page.
In synchronous mode, you can explicitely set a return value with a call to `$response->setReturnValue()` in your Jaxon PHP function or class.

**Comment by jatubio** [comment]
Thank you for your response. I think that I don't want to change ˋjaxon.config.defaultReturnValueˋ. I'm using ˋ$response->setReturnValue()ˋ in my php code.

Then, probably I have to change the generated code for ˋjaxon_formRegistroˋ function to be synchronous. ¿How can I do it?

**Comment by jatubio** [comment]
If someone have the same question, you have to change the code for register your function to make the call synchronous.

$jaxon->register(Jaxon::USER_FUNCTION, 'helloWorld', array('mode' => "'synchronous'"));
$jaxon->register(Jaxon::USER_FUNCTION, 'setColor', array('mode' => "'synchronous'"));
